site_name: FastApi-MAIL
site_url: 
site_description: fastapi-mail 
dev_addr: 127.0.0.1:8080

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: purple
  
  icon:
    repo: fontawesome/brands/github


    
repo_name: fastapi-mail
repo_url: https://github.com/sabuhish/fastapi-mail
edit_uri: ''

plugins:
- search
- markdownextradata:
    data: data

markdown_extensions:
  - toc:
      permalink: true
  
  - pymdownx.highlight:
      linenums: false

  - pymdownx.superfences

nav:
  - FastApi MAIL: index.md
  - 🔨 Installation: install.md
  - 🕹 Getting Started: getting-started.md
  - Example: example.md
  - Contribution: contribute.md


